-- MySQL Script generated by MySQL Workbench
-- Thu 18 Feb 2016 15:27:24 UTC
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sensorbase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sensorbase` ;

-- -----------------------------------------------------
-- Table `zones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `date_added` DATETIME NOT NULL,
  `date_modified` DATETIME NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations` (
  `id` INT NOT NULL,
  `zone_id` INT NOT NULL,
  `lattitude` DECIMAL(11,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `date_added` DATETIME NOT NULL,
  `date_modified` DATETIME NULL,
  `zones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locations_zones_idx` (`zones_id` ASC),
  CONSTRAINT `fk_locations_zones`
    FOREIGN KEY (`zones_id`)
    REFERENCES `zones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensor_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensor_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `date_added` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location_id` INT NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `last` DATETIME NOT NULL,
  `date_added` DATETIME NOT NULL,
  `date_modified` DATETIME NULL,
  `sensor_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensors_locations1_idx` (`location_id` ASC),
  INDEX `fk_sensors_sensor_types1_idx` (`sensor_type_id` ASC),
  CONSTRAINT `fk_sensors_locations1`
    FOREIGN KEY (`location_id`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensors_sensor_types1`
    FOREIGN KEY (`sensor_type_id`)
    REFERENCES `sensor_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensor_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensor_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sensor_id` INT NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `sequence` INT(11) NOT NULL,
  `last` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensor_data_sensors1_idx` (`sensor_id` ASC),
  CONSTRAINT `fk_sensor_data_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_added` DATETIME NOT NULL,
  `zone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stations_zones1_idx` (`zone_id` ASC),
  CONSTRAINT `fk_stations_zones1`
    FOREIGN KEY (`zone_id`)
    REFERENCES `zones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
