#+TITLE: Presentation
#+DATE: <2016-02-19 Fri>
#+AUTHOR:Mc Spud Rat
#+EMAIL: pi@pi-a
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:t todo:t |:t
#+CREATOR: Emacs 24.4.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export

* Introduction

** Liam
Second year Software Development student at Cornwall College.

** Naomi
Second year Software Development student at Cornwall College.
** Shane
First year computing student at Cornwall College.
** Emo
Third year networking computing student at Cornwall College.
** Ben
Indie programmer based in Newquay.

* The plan for Eden

*
* What did we need to achieve?
Our aim was to create a system in which the two other teams could use.

The sensor team needed to be able to post sensor data to the database,
and the AV team needed to be able to retrieve this data, and use it in
their visual presentations.

This meant that we needed to create a functioning database, linking multiple
tables in order to store information about the sensors and their locations
as well as

* Our Journey


* Our product

** Active up time monitoring

** DRY compliant database schema

** API

** Security

* Any Questions?
